bvc/urls.py
from django.conf.urls import url

from . import views

app_name = 'bvc'
urlpatterns = [
    url(r'^$', views.member.home, name='home'),
    url(r'^commander/adherent$', views.member.command_member, name='command_member'),
    url(r'^commander/commission$', views.member.command_commission, name='command_commission'),
]

gucem/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^bvc/', include('bvc.urls')),
    url(r'^admin/', admin.site.urls),
]

bvc/models/command.py
from django.db import models

class AbstractCommand(models.Model):
    amout = models.PositiveSmallIntegerField(default=0)
    datetime = models.DateTimeField(auto_now_add=True)
    email = models.EmailField()
    comments = models.TextField(default='')

class MemberCommand(AbstractCommand):
    ESMUG = 'esmug'
    GUCEM = 'gucem'

    PLACED_STATE = 'placed'
    PREPARED_STATE = 'prepared'
    SOLD_STATE = 'sold'
    CASHED_STATE = 'cashed'
    CANCELED_STATE = 'canceled'

    CLUB_CHOICES = (
        (GUCEM, 'GUCEM'),
        (ESMUG, 'ESMUG'),
    )

    STATE_CHOICES = (
        (PLACED_STATE, 'Commande effectuée'),
        (PREPARED_STATE, 'Commande préparée'),
        (SOLD_STATE, 'Commande vendue'),
        (CASHED_STATE, 'Commande encaissée'),
        (CANCELED_STATE, 'Commande annulée'),
    )

    lastname = models.CharField(max_length=30,)
    firstname = models.CharField(max_length=30,)
    license = models.CharField(max_length=12,)
    club = models.CharField(
        max_length=max(len(choice[0]) for choice in CLUB_CHOICES),
        choices=CLUB_CHOICES,
        default=GUCEM,
    )
    state = models.CharField(
        max_length=max(len(choice[0]) for choice in STATE_CHOICES),
        choices=STATE_CHOICES,
        default=PLACED_STATE,
    )

class CommissionCommand(AbstractCommand):
    CANYONING = 'canyoning'
    CLIMBING = 'climbing'
    CAVING = 'caving'
    MOUNTAINEERING = 'mountaineering'

    PLACED_STATE = 'placed'
    PREPARED_STATE = 'prepared'
    SOLD_STATE = 'sold'

    COMMISSION_CHOICES = (
        (CANYONING, 'Canyoning'),
        (CLIMBING, 'Escalade'),
        (CAVING, 'Spéléologie'),
        (MOUNTAINEERING, 'Alpinisme'),
    )

    STATE_CHOICES = (
        (PLACED_STATE, 'Commande effectuée'),
        (PREPARED_STATE, 'Commande préparée'),
        (SOLD_STATE, 'Commande distribuée'),
    )

    commission = models.CharField(
        max_length=max(len(choice[0]) for choice in COMMISSION_CHOICES),
        choices=COMMISSION_CHOICES,
        default=CANYONING,
    )
    state = models.CharField(
        max_length=max(len(choice[0]) for choice in STATE_CHOICES),
        choices=STATE_CHOICES,
        default=PLACED_STATE,
    )

bvc/views/member.py
from django.shortcuts import render

def home(request):
    return render(request, 'bvc/home.html')

def command_commission(request):
    return render(request, 'bvc/command_commission.html')

def command_member(request):
    return render(request, 'bvc/command_member.html')

bvc/templates/bvc/command_commission.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Commandes BVC commission{% endblock %}

{% block contents %}
<p>Commandes commissions</p>
{% endblock %}

bvc/templates/bvc/command_member.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Commandes BVC adhérent{% endblock %}

{% block contents %}
<p>Commandes adhérents</p>
{% endblock %}

bvc/templates/bvc/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}BVC{% endblock %}

{% block contents %}
<p>Page d'accueil des BVC</p>

<a href="{% url 'bvc:command_member' %}">Commandes adhérents</a>
<br/>
<a href="{% url 'bvc:command_commission' %}">Commandes commissions</a>
{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8"/>
  <title>{% block title %}{% endblock %} | GUCEM</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
  {% block style %}{% endblock %}
</head>
<body>
  <header>
    Un header commun

    <nav>
      <ul>
        <li><a href="{% url 'bvc:home' %}">BVC</a></li>
      </ul>
    </nav>
  </header>

  <div id="contents">{% block contents %}{% endblock %}</div>

  {% block javascript %}{% endblock %}
</body>
</html>